# server配置
server:
  port: 8000
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///bigHealth
      username: root  #开发环境
      password: 123456wmr
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置静态资源访问，允许通过 URL 访问上传的图片
  web:
    resources:
      static-locations: /Users/wunder/file:upload-files/

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: edu.whut.pojo
  global-config:
    db-config:
      version-field: version # 乐观锁字段
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长

# 文件上传的保存目录，确保项目根目录下有 `upload-files` 文件夹
upload:
  directory: /Users/wunder/upload-files


